"""Configuration for literature review search pipeline."""

import os

NCBI_EMAIL = os.environ.get("NCBI_EMAIL", "vignesh.ravichandran@rutgers.edu")
NCBI_API_KEY = os.environ.get("NCBI_API_KEY", "")
SEMANTIC_SCHOLAR_API_KEY = os.environ.get("SEMANTIC_SCHOLAR_API_KEY", "")

PUBMED_BASE = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
BIORXIV_BASE = "https://api.biorxiv.org/"
EUROPEPMC_BASE = "https://www.ebi.ac.uk/europepmc/webservices/rest/"
SEMANTIC_SCHOLAR_BASE = "https://api.semanticscholar.org/graph/v1/"

# Rate limits (seconds between requests)
PUBMED_DELAY = 0.35 if NCBI_API_KEY else 1.0
BIORXIV_DELAY = 1.0
EUROPEPMC_DELAY = 0.5
SS_DELAY = 3.5  # 100 req / 5 min = ~3s between

CACHE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "cache")

TIER1_JOURNALS = {
    "Nature", "Cell", "Science", "Nature medicine", "Cancer cell",
    "Nature genetics", "Nature cancer", "Nature methods",
    "Nature communications", "Cell reports", "Immunity",
    "The New England journal of medicine", "Lancet (London, England)",
    "JAMA", "The Lancet. Oncology", "Journal of clinical oncology",
    "Nature reviews. Cancer", "Nature reviews. Clinical oncology",
    "Nature reviews. Drug discovery", "The Lancet",
    "The Lancet Oncology", "Journal of Clinical Oncology",
    "Nature Medicine", "Cancer Cell", "Nature Genetics",
    "Nature Cancer", "Nature Methods", "Nature Communications",
    "Cell Reports", "New England Journal of Medicine",
    "JAMA oncology", "JAMA Oncology",
}

TIER2_JOURNALS = {
    "Cancer research", "Clinical cancer research",
    "Genome medicine", "Genome biology", "Bioinformatics",
    "Briefings in bioinformatics", "npj precision oncology",
    "Annals of oncology", "Journal of thoracic oncology",
    "Molecular cancer", "Nucleic acids research",
    "Cell reports medicine", "Cancer Research",
    "Clinical Cancer Research", "Genome Medicine", "Genome Biology",
    "Briefings in Bioinformatics", "npj Precision Oncology",
    "Annals of Oncology", "Journal of Thoracic Oncology",
    "Molecular Cancer", "Nucleic Acids Research",
    "Cell Reports Medicine", "Science translational medicine",
    "Science Translational Medicine",
}

TIER3_JOURNALS = {
    "Frontiers in oncology", "Frontiers in immunology",
    "Scientific reports", "PloS one", "Cancers",
    "International journal of molecular sciences", "BMC cancer",
    "Journal of translational medicine",
    "Translational lung cancer research", "Lung cancer",
    "Frontiers in Oncology", "Frontiers in Immunology",
    "Scientific Reports", "PLoS ONE", "Cancers (Basel)",
    "Int J Mol Sci", "BMC Cancer", "Journal of Translational Medicine",
    "Translational Lung Cancer Research", "Lung Cancer",
}

PREDATORY_PUBLISHERS = {
    "OMICS International", "Scientific Research Publishing",
    "SCIRP",
}

FLAGGED_PUBLISHERS = {"Hindawi"}

# Anchor PMIDs per theme
ANCHOR_PMIDS = {
    "theme_01": ["25079552", "22960745", "26168399", "31406302",
                 "32649874", "32649875", "32649877", "38181741",
                 "30926931", "33011388"],
    "theme_02": ["32185779", "28369062", "19759197", "24464287",
                 "32393329", "30590492", "33524135"],
    "theme_03": [],
    "theme_04": ["30224757", "35944502", "39294368", "39030412",
                 "36108632", "35512792"],
    "theme_05": ["29778737", "32350439"],
    "theme_06": ["17667967", "34493867"],
    "theme_07": ["37046093", "23900102"],
    "theme_08": [],
    "theme_09": ["29628290", "28052254", "34019806", "25765070",
                 "33479125"],
    "theme_10": [],
    "theme_11": [],
    "theme_12": ["29988129", "32015526"],
}

ALL_ANCHOR_PMIDS = set()
for v in ANCHOR_PMIDS.values():
    ALL_ANCHOR_PMIDS.update(v)

# Theme definitions
THEMES = {
    "theme_01": {
        "name": "Lung cancer molecular heterogeneity foundations",
        "dir": "theme_01_heterogeneity",
        "min_target": 100,
        "keywords": ["lung cancer", "molecular", "heterogeneity", "subtype",
                      "LUAD", "LUSC", "SCLC", "driver mutation", "genomic landscape",
                      "multi-omics", "proteogenomic", "TCGA", "EGFR", "KRAS",
                      "TP53", "ALK", "co-mutation", "histologic transformation"],
        "queries": [
            '(lung adenocarcinoma[MeSH] OR LUAD) AND (molecular subtype OR multi-omics OR integrative)',
            '(lung squamous cell carcinoma OR LUSC) AND (molecular OR genomic) AND subtype',
            '"small cell lung cancer" AND (genomic OR molecular subtype)',
            '"small cell lung cancer" AND (ASCL1 OR NEUROD1 OR POU2F3 OR YAP1)',
            'NSCLC AND (genomic landscape OR mutational landscape)',
            'lung adenocarcinoma AND (EGFR OR KRAS OR TP53 OR ALK) AND (co-mutation OR comutation)',
            'lung cancer AND tumor heterogeneity AND molecular',
            'lung cancer AND driver mutation AND subtype',
            '"lung adenocarcinoma in situ" OR "minimally invasive adenocarcinoma"',
            'TCGA AND lung AND (genomic OR molecular)',
            'lung cancer AND proteogenomic',
            'lung cancer AND histologic transformation',
        ],
    },
    "theme_02": {
        "name": "Multi-omics integration methods",
        "dir": "theme_02_methods",
        "min_target": 100,
        "keywords": ["multi-omics", "integration", "method", "benchmark",
                      "clustering", "deep learning", "autoencoder", "graph neural network",
                      "factor analysis", "NMF", "canonical correlation",
                      "MOVICS", "DIABLO", "iCluster", "MOFA", "SNF"],
        "queries": [
            'multi-omics integration AND (benchmark OR comparison OR evaluation)',
            '"MOVICS" OR "DIABLO" OR "iCluster" OR "MOFA" OR "NEMO"',
            '"similarity network fusion" OR "SNF" cancer',
            'multi-omics clustering AND consensus',
            'integrative omics AND method AND cancer',
            'multi-omics AND deep learning AND integration',
            'variational autoencoder AND multi-omics',
            'graph neural network AND multi-omics AND cancer',
            'multi-modal AND deep learning AND cancer',
            'multi-omics factor analysis',
            'joint NMF AND multi-omics',
            '"late integration" OR "early integration" multi-omics cancer',
            'canonical correlation analysis AND omics',
            'Bayesian AND multi-omics AND cancer',
        ],
    },
    "theme_03": {
        "name": "Multi-omics applications in lung cancer",
        "dir": "theme_03_applications",
        "min_target": 100,
        "keywords": ["multi-omics", "lung cancer", "proteogenomic", "integrative",
                      "subtype", "classification", "immunotherapy", "prognosis",
                      "drug response", "tumor microenvironment", "survival"],
        "queries": [
            'multi-omics AND lung cancer AND (subtype OR classification OR clustering)',
            'proteogenomic AND lung cancer',
            'integrative AND (transcriptome OR methylome OR proteome) AND (LUAD OR LUSC OR SCLC)',
            'multi-platform AND lung adenocarcinoma',
            'multi-omics AND NSCLC AND immunotherapy',
            'multi-omics AND lung cancer AND prognosis',
            'multi-omics AND lung cancer AND drug response',
            'integrative genomics AND lung cancer AND survival',
            'multi-omics AND tumor microenvironment AND lung',
            'multi-omics AND radiation therapy AND lung',
            'proteogenomics AND NSCLC AND driver',
            'multi-omics AND early detection AND lung',
        ],
    },
    "theme_04": {
        "name": "AI/ML in lung cancer and oncology",
        "dir": "theme_04_ai_ml",
        "min_target": 150,
        "keywords": ["machine learning", "deep learning", "artificial intelligence",
                      "neural network", "classification", "histopathology",
                      "radiomics", "radiogenomics", "immunotherapy", "prediction",
                      "foundation model", "transformer", "survival", "prognosis",
                      "validation", "bias", "reproducibility", "whole slide image"],
        "queries": [
            'machine learning AND lung cancer AND (subtype OR classification)',
            'deep learning AND NSCLC AND classification',
            'unsupervised learning AND lung cancer AND molecular',
            'deep learning AND lung cancer AND histopathology',
            'convolutional neural network AND NSCLC AND pathology',
            'whole slide image AND lung cancer AND deep learning',
            'self-supervised learning AND pathology AND cancer',
            'radiogenomics AND lung cancer',
            'radiomics AND NSCLC AND (survival OR response)',
            'radiomics AND immunotherapy AND lung',
            'artificial intelligence AND immunotherapy response AND (lung OR NSCLC)',
            'machine learning AND checkpoint inhibitor AND lung cancer',
            'deep learning AND PD-L1 AND lung',
            'foundation model AND (pathology OR oncology)',
            'large language model AND oncology',
            'transformer AND pathology AND cancer',
            'vision language model AND pathology',
            'multi-modal AND deep learning AND oncology',
            'multi-omics AND machine learning AND cancer',
            'fusion model AND cancer AND outcome',
            'deep learning AND survival AND lung cancer',
            'machine learning AND prognosis AND NSCLC',
            'neural network AND survival prediction AND cancer',
            'external validation AND machine learning AND cancer',
            'bias AND machine learning AND clinical AND cancer',
            'reproducibility AND AI AND oncology',
            'generalizability AND deep learning AND medical imaging',
        ],
    },
    "theme_05": {
        "name": "Sex and gender differences in lung cancer",
        "dir": "theme_05_sex",
        "min_target": 75,
        "keywords": ["sex differences", "gender", "estrogen", "female",
                      "women", "sex hormone", "Y chromosome", "lung cancer",
                      "disparity", "immunotherapy", "survival", "biomarker"],
        "queries": [
            'sex differences AND lung cancer AND (molecular OR outcome)',
            'estrogen receptor AND (NSCLC OR lung adenocarcinoma)',
            'gender disparity AND immunotherapy AND lung cancer',
            'female AND lung adenocarcinoma AND EGFR AND never smoker',
            'sex hormone AND lung cancer',
            'pregnancy AND lung cancer',
            'sex chromosome AND cancer AND lung',
            'Y chromosome loss AND lung cancer',
            'gender AND survival AND NSCLC',
            'women AND lung cancer AND epidemiology',
            'sex-specific AND biomarker AND lung cancer',
        ],
    },
    "theme_06": {
        "name": "Never-smoker lung cancer",
        "dir": "theme_06_never_smoker",
        "min_target": 75,
        "keywords": ["never smoker", "non-smoking", "nonsmoking", "light smoker",
                      "EGFR", "ALK", "ROS1", "lung cancer", "genomic",
                      "molecular", "mutational signature", "secondhand smoke"],
        "queries": [
            'never smoker AND lung cancer AND (genomic OR molecular)',
            'non-smoking lung adenocarcinoma AND (Asian OR East Asian)',
            'EGFR mutation AND never smoker AND epidemiology',
            'lung cancer etiology AND never smoker',
            'ALK fusion AND never smoker',
            'ROS1 AND never smoker AND lung',
            'lung cancer AND light smoker AND molecular',
            'tumor microenvironment AND never smoker AND lung',
            'immunotherapy response AND never smoker AND lung',
            'lung cancer AND mutational signature AND smoking',
            'second-hand smoke AND lung cancer',
            'never-smoker AND brain metastasis AND lung',
        ],
    },
    "theme_07": {
        "name": "Environmental exposures and lung cancer",
        "dir": "theme_07_environment",
        "min_target": 75,
        "keywords": ["PM2.5", "air pollution", "radon", "asbestos", "silica",
                      "occupational", "indoor", "cooking fume", "diesel exhaust",
                      "PFAS", "exposome", "wildfire", "lung cancer", "environmental"],
        "queries": [
            'PM2.5 AND lung cancer AND (mutation OR epigenetic OR EGFR)',
            'radon AND lung cancer AND (molecular OR risk)',
            'air pollution AND lung cancer AND incidence',
            'occupational exposure AND lung cancer',
            'asbestos AND lung cancer AND molecular',
            'indoor air pollution AND lung cancer',
            'cooking fume AND lung cancer',
            'secondhand smoke AND lung cancer AND molecular',
            'diesel exhaust AND lung cancer',
            'PFAS AND cancer AND lung',
            'exposome AND lung cancer',
            'silica AND lung cancer',
            'pollution AND EGFR mutation AND lung',
            'wildfire smoke AND cancer',
        ],
    },
    "theme_08": {
        "name": "Epigenetics in lung cancer",
        "dir": "theme_08_epigenetics",
        "min_target": 75,
        "keywords": ["DNA methylation", "epigenetic", "miRNA", "histone",
                      "chromatin", "ATAC-seq", "lncRNA", "circRNA",
                      "methylation signature", "enhancer", "cfDNA methylation",
                      "lung cancer"],
        "queries": [
            'DNA methylation AND lung cancer AND (subtype OR survival OR prognosis)',
            'epigenetic AND lung adenocarcinoma AND molecular',
            'miRNA AND lung cancer AND (prognosis OR therapy)',
            'histone modification AND lung cancer',
            'chromatin accessibility AND lung cancer',
            'ATAC-seq AND lung cancer',
            'lncRNA AND lung cancer AND prognosis',
            'methylation signature AND NSCLC AND biomarker',
            'epigenome-wide association AND lung cancer',
            'circRNA AND lung cancer',
            'AHRR hypomethylation AND lung',
            'cfDNA methylation AND lung cancer',
            'enhancer AND lung cancer',
        ],
    },
    "theme_09": {
        "name": "Immune biomarkers and immunotherapy response",
        "dir": "theme_09_immune_biomarkers",
        "min_target": 75,
        "keywords": ["PD-L1", "tumor mutational burden", "TMB", "immunotherapy",
                      "immune", "checkpoint inhibitor", "tumor microenvironment",
                      "neoantigen", "T cell", "HLA", "gene expression signature",
                      "STK11", "KEAP1", "microbiome", "lung cancer"],
        "queries": [
            'PD-L1 AND NSCLC AND (limitation OR heterogeneity OR resistance)',
            'tumor mutational burden AND immunotherapy AND lung cancer',
            '"Immunophenoscore" OR "Tempus IPS"',
            'immune subtype AND pan-cancer',
            'tumor microenvironment AND immunotherapy AND NSCLC',
            'HLA AND immunotherapy response',
            'gene expression signature AND immunotherapy AND lung',
            'neoantigen AND lung cancer AND immunotherapy',
            'MSI AND lung cancer AND immunotherapy',
            'T cell inflamed AND lung cancer',
            'Thorsson immune landscape cancer',
            'Bagaev conserved microenvironment',
            'Charoentong immunogenomic',
            'STK11 AND KEAP1 AND immunotherapy AND NSCLC',
            'gut microbiome AND immunotherapy AND response',
        ],
    },
    "theme_10": {
        "name": "Targeted therapy access, translational bottleneck, real-world outcomes",
        "dir": "theme_10_translational",
        "min_target": 75,
        "keywords": ["precision oncology", "real-world", "targeted therapy",
                      "disparity", "biomarker testing", "clinical trial",
                      "molecular tumor board", "implementation", "guideline",
                      "ancestry", "socioeconomic", "lung cancer"],
        "queries": [
            'precision oncology AND real-world AND lung cancer',
            'targeted therapy AND utilization AND NSCLC',
            'biomarker testing AND disparity AND lung cancer',
            'clinical trial representation AND (women OR minority) AND cancer',
            'health disparity AND lung cancer',
            'molecular tumor board AND outcome',
            'real-world evidence AND NSCLC AND immunotherapy',
            'implementation science AND precision oncology',
            'access AND targeted therapy AND oncology',
            'guideline adherence AND NSCLC',
            'ancestry AND clinical trial AND cancer',
            'socioeconomic AND lung cancer AND outcome',
            'Flatiron AND NSCLC',
            'MYLUNG consortium',
            'EGFR TKI AND treatment landscape',
            'KRAS G12C AND sotorasib OR adagrasib',
        ],
    },
    "theme_11": {
        "name": "Drug repurposing in oncology",
        "dir": "theme_11_drug_repurposing",
        "min_target": 75,
        "keywords": ["drug repurposing", "repositioning", "drug-gene interaction",
                      "connectivity map", "pharmacogenomic", "GDSC", "CCLE",
                      "drug sensitivity", "synthetic lethality", "network pharmacology",
                      "DGIdb", "PRISM", "drug combination", "lung cancer"],
        "queries": [
            'drug repurposing AND cancer AND (computational OR multi-omics)',
            'drug-gene interaction AND cancer AND prediction',
            '"dimethyl fumarate" AND KEAP1 AND cancer',
            'connectivity map AND cancer',
            'pharmacogenomic AND lung cancer',
            'GDSC AND drug response AND cancer',
            'CCLE AND drug AND lung',
            'drug sensitivity AND lung cancer AND biomarker',
            'synthetic lethality AND lung cancer',
            'network pharmacology AND cancer',
            'DGIdb drug gene interaction',
            'repositioning AND oncology',
            'PRISM drug screen',
            'drug combination AND lung cancer AND computational',
        ],
    },
    "theme_12": {
        "name": "Single-cell, spatial, metabolomic, liquid biopsy frontiers",
        "dir": "theme_12_emerging_frontiers",
        "min_target": 75,
        "keywords": ["single-cell", "scRNA-seq", "spatial transcriptomics",
                      "spatial proteomics", "metabolomics", "lipidomics",
                      "liquid biopsy", "ctDNA", "cfDNA", "minimal residual disease",
                      "CAPP-Seq", "microbiome", "Visium", "CODEX", "lung cancer"],
        "queries": [
            'single-cell RNA AND lung cancer AND heterogeneity',
            'single-cell AND NSCLC AND tumor microenvironment',
            'scRNA-seq AND lung adenocarcinoma',
            'spatial transcriptomics AND lung cancer',
            'spatial proteomics AND lung cancer',
            'imaging mass cytometry AND lung cancer',
            'Visium AND lung cancer',
            'CODEX AND lung cancer',
            'metabolomics AND lung cancer AND biomarker',
            'lipidomics AND lung cancer',
            'tryptophan metabolism AND lung cancer',
            'liquid biopsy AND lung cancer AND (methylation OR ctDNA)',
            'cfDNA AND lung cancer AND early detection',
            'minimal residual disease AND lung cancer',
            'CAPP-Seq AND lung',
            'microbiome AND lung cancer',
            'gut microbiome AND immunotherapy AND lung',
        ],
    },
}
